services:
  - type: web
    name: signsync
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 4 --timeout 120 app:app
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.10.0
